In [ ]:
#RA2311056010307

In [5]:
#create a 5d array
import numpy as np
x=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
x.shape


(3, 4)

In [6]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [7]:
x.strides

(16, 4)

In [8]:
x.ndim

2

In [9]:
x.data

In [11]:
x.size


12

In [12]:
x.itemsize

4

In [15]:
x.base

In [16]:
x.nbytes

48

In [17]:
x.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [18]:
x.real

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
x.imag

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])